<!DOCTYPE html>
<html>
<head>
    <title>ูููุนู</title>
    <link rel="stylesheet" type="text/css" href="hob.css">
</head>
<body>
    <header>
        <h1>ูุฑุญุจูุง ุจู ูู ูููุนู</h1>
    </header>

    <nav>
        <ul>
            <li><a href="index.html">ุงูุฑุฆูุณูุฉ</a></li>
            <li><a href="ุตูุฑ.html">ุงูุตูุฑ</a></li>
            <li><a href="ููุฏูู.html">ุงูููุฏูู</a></li>
            <li><a href="ุฃุบุงูู.html">ุงูุฃุบุงูู</a></li>
        </ul>
    </nav>

    <section>
        <h2>ูุญุชูู ุงูุตูุญุฉ</h2>
        <p>ูุฐุง ูุซุงู ุนูู ูุต ูู ูุญุชูู ุงูุตูุญุฉ. ููููู ุฅุถุงูุฉ ุงููุฒูุฏ ูู ุงููุญุชูู ููุง.</p>
    </section>
</body>
</html>
<html>
<head>
    <title>ูุนุฑุถ ุงูุตูุฑ</title>
</head>
<body>
    <h1>ูุนุฑุถ ุงูุตูุฑ</h1>

    <div class="gallery">
        <img src="/storage/emulated/0/Pictures/facebook/1697854265074.jpg" alt="ุตูุฑุฉ 1">
        <img src="/storage/emulated/0/Pictures/facebook/1697854258700.jpg" alt="ุตูุฑุฉ 2">
        <img src="/storage/emulated/0/Pictures/facebook/1697853695631.jpg" alt="ุตูุฑุฉ 3">
        <img src="/storage/emulated/0/Pictures/Picsart/Picsart_23-10-17_11-04-35-599.jpg" alt="ุตูุฑุฉ 4">
        <img src="/storage/emulated/0/DCIM/Screenshots/Screenshot_20231021_130553_Instagram.jpg" alt="ุตูุฑุฉ 5">
    </div>
</body>
</html>
<!DOCTYPE html>
<html>
<head>
    <title>GHOST</title>
</head>
<body>
    <h1>ุณูู ุงูุชูู ูููู ุฌููุนุง ุงูุชุถุฑููู๐</h1>

    <video controls>
        <source src="/storage/emulated/0/DCIM/Camera/lv_0_20231021040324.mp4" type="audio/mp4">
        Your browser does not support the video tag.
    </video>
</body>
</html>
